manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: chormbos
      import: app/west.yml
  self:
    path: config
